apiVersion: v1
kind: Service
metadata:
  name: vote-<your-name>
  namespace: vote-<your-name>
spec:
  type: NodePort
  ports:
  - name: "vote-<your-name>-service"
    port: 5000
    targetPort: 80
  selector:
    app: vote-<your-name>
  
